-- Blog EN columns
ALTER TABLE "blogs" ADD COLUMN IF NOT EXISTS "titleEn" TEXT;
ALTER TABLE "blogs" ADD COLUMN IF NOT EXISTS "contentEn" TEXT;
ALTER TABLE "blogs" ADD COLUMN IF NOT EXISTS "excerptEn" TEXT;

-- User isDeleted
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;

-- Role soft delete
ALTER TABLE "roles" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "roles" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
